# Generated by Django 5.2.1 on 2025-05-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_students_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
